### ISSUE TITLE
DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by hathaway** [altodd/Southwest-Docker#1] opened 2022-02-07 19:43 UTC
Hello,

Thanks for your work on this. I was considering making this docker myself but came across yours and it was exactly what I was planning to make.

I'm running into an issue when I try to run it though. It's related to the ChromeDriver. 

I ran the command:

`docker run --platform linux/amd64 -itd altodd/southwest-docker schedule ABCXYZ John Doe`

And got the output:

```Starting deferred execution scheduler: atd.

Starting periodic command scheduler: cron.

Traceback (most recent call last):

  File "/headers/southwest-headers/southwest-headers.py", line 37, in <module>

    driver = webdriver.Chrome(os.getcwd() + "/chromedriver", options=chrome_options, seleniumwire_options=seleniumwire_options)

  File "/headers/southwest-headers/env/lib/python3.9/site-packages/seleniumwire/webdriver.py", line 195, in __init__

    super().__init__(*args, **kwargs)

  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__

    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",

  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__

    RemoteWebDriver.__init__(

  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__

    self.start_session(capabilities, browser_profile)

  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session

    response = self.execute(Command.NEW_SESSION, parameters)

  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute

    self.error_handler.check_response(response)

  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response

    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.

  (unknown error: DevToolsActivePort file doesn't exist)

  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

Specifically, it seems to be caused by `unknown error: DevToolsActivePort file doesn't exist` which is [related to running Chrome as root](https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t). It appears [southwest-headers factors this in](https://github.com/byalextran/southwest-headers/blob/0dd4ac4e2ea50872638499b5b14673aa4b5fa60b/southwest-headers.py#L29).

Did you run into this issue? Any ideas? Thanks!

**Comment by altodd** [comment] 2022-02-08 04:04
Hey,

I can check it out tomorrow, but I haven’t had that issue. I just recently
had a flight and didn’t get the email (although seemingly successful
putting my in the mid A’s) so I was planning to look at that. I run it on a
Linux server without the - -platform flag, since that’s the only difference
I see I suspect that’s the culprit but I’m not sure why specifying the
platform would cause that.

Thanks

**Comment by hathaway** [comment] 2022-02-08 04:58
I get the same result without that flag. I added that because it gives a warning about the platform on an M1 MacBook Pro without it. Thanks for taking a look.

**Comment by altodd** [comment] 2022-02-11 03:28
Okay, everything is looking good to me, but I am running the container on a debian based server - although in an ideal world that shouldn't matter. Are you able to just run the base debian image on your mac?

**Comment by altodd** [comment] 2022-03-11 18:41
Haven't been able to reproduce, closing

**Closed as completed by altodd** 2022-03-11 18:41 UTC

**Comment by altodd** [comment] 2022-03-11 19:00
I did see you forked the repository, if you are able to figure anything out as to why it's causing the issue on your end please make a pull request/update this and I'll modify the image I have on dockerhub
